language: python

cache: pip

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy3"

# services:
#   - postgresql

install:
  - pip install -r requirements.txt
  - pip install --upgrade git+https://github.com/mideind/Tokenizer#egg=tokenizer
  - pip install --upgrade git+https://github.com/mideind/GreynirPackage#egg=reynir
  - pip install --upgrade git+https://github.com/mideind/GreynirCorrect#egg=reynir-correct

before_script:
  # Configure locale
  - sudo apt-get install language-pack-is
  - sudo locale-gen is_IS.UTF-8
  - sudo update-locale
  # Start postgres and init database
  - sudo systemctl start postgresql
  - psql -c "create database scraper with encoding 'UTF8' LC_COLLATE='is_IS.UTF-8' LC_CTYPE='is_IS.UTF-8' TEMPLATE=template0;" -U postgres
  - psql -d scraper -c "create extension if not exists \"uuid-ossp\";" -U postgres
  - psql -c "create user reynir with password 'reynir';" -U postgres
  - python scraper.py --init
  # Insert dummy database data from CSV files
  - cp tests/test_files/testdb_articles.csv /tmp/
  - psql -d scraper -c "copy articles from '/tmp/testdb_articles.csv' delimiter ',' csv;"
  - cp tests/test_files/testdb_persons.csv /tmp/
  - psql -d scraper -c "copy persons from '/tmp/testdb_persons.csv' delimiter ',' csv;"
  - cp tests/test_files/testdb_queries.csv /tmp/
  - psql -d scraper -c "copy queries from '/tmp/testdb_queries.csv' delimiter ',' csv;"
  - cp tests/test_files/testdb_querydata.csv /tmp/
  - psql -d scraper -c "copy querydata from '/tmp/testdb_querydata.csv' delimiter ',' csv;"
  # Create dummy Greynir API key
  - cat "tests/test_files/dummy_greynir_api_key.txt" > "resources/GreynirServerKey.txt"
  # Install jshint for for JavaScript linting
  - npm i -g jshint

script:
  - python -m pytest
  - jshint static/js/common.js

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
